version: 2
jobs:
  build:
    docker:
      - image: clojure:lein-2.9.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "37:cc:ad:b6:53:7a:98:22:83:fb:d8:77:12:cf:8c:92"
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: lein test-all
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: << checksum "project.clj" >>
