version: 2
jobs:
  build:
    docker:
      - image: clojure:openjdk-8-lein-2.9.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a6:08:d9:a8:b8:92:c3:d2:19:f4:0b:af:a6:8b:2b:7c"
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: lein test-all
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: << checksum "project.clj" >>
